apiVersion: v1
kind: Service
metadata:
  name: "{{ include "fizzbuzz.fullname" . }}"
  labels:
    {{- include "fizzbuzz.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.basePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fizzbuzz.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "fizzbuzz1.fullname" . }}"
  labels:
    {{- include "fizzbuzz.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ add .Values.service.basePort 1 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fizzbuzz1.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "fizzbuzz2.fullname" . }}"
  labels:
    {{- include "fizzbuzz.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ add .Values.service.basePort 2 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fizzbuzz2.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "fizzbuzz3.fullname" . }}"
  labels:
    {{- include "fizzbuzz.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ add .Values.service.basePort 3 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fizzbuzz3.selectorLabels" . | nindent 4 }}
